### PR TITLE
KAFKA-6252: Close the metric group to clean up any existing metrics

### PR DESCRIPTION
**Pull request by wicknicks**
Signed-off-by: Arjun Satish <arjun@confluent.io>

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rhauch — COMMENTED** [review]
@wicknicks this looks like an acceptable approach. However, we probably want to do the same thing in WorkerSourceTask, too, since that will likely fail for a similar reason. We should also verify that sink tasks don't have a similar problem; if so then WorkerSinkTask might need to be addressed, too.

We may want to do all three of these, just to be on the safe side. Thoughts?

**Comment by wicknicks** [comment]
Yeah, that's a good point. Once the `WorkerTask` metrics are successfully created, the source/sink metrics will be re-initialized, which will throw an exception. Would we need to do this in `WorkerConnector` as well?

Another thought is whether we want to not throw an Exception if for the same metric name, we are initializing the same type of value provider. What do you think? Or add a less cranky `addOrGet` alternative to the `add` method in MetricGroup.

**Comment by rhauch** [comment]
I'm not sure why throwing an exception would help. Aren't we trying to get rid of an exception being thrown? :-)

Adding another "less cranky" method may be useful, but OTOH it's easy enough to call `close()` on the resulting metric group before using it. I almost prefer the latter since it is simpler overall.

**Comment by wicknicks** [comment]
Ah, I meant to say "the exception will happen", and therefore we need to add the changes there as well. Missed out a bunch of words. heh.

Let me make a PR for this, and put it up tomorrow AM.

**Pull request closed without merging**
